### ISSUE TITLE
Unnecessary 'source/packages' folder

### ISSUE THREAD

**Issue by Kosat** [Dirkster99/MRULib#1]
Hi, 
Thanks for sharing your code. Good job! 

There's yet a small glitch I'd like to point out.  I noticed that you included 
https://github.com/Dirkster99/MRULib/tree/master/source/packages . The better practice, however, is to just include packages.config, witch you did, and let people restore the packages themselves. 
The `source/packages` folder should also be included in *.gitingnore* file. 

BTW, GitHub offers a nice VisualStudio *.gitingnore* template when you create a new repository.

**Comment by Dirkster99** [comment]
Hi Kosat,

thanks for the good feedback - thats always refreshing after being done with so much work :-)
I removed the packages folder and updated .gitignore to ignore the packages folder in source and at root level for good measure.

Please let me know if this OK for you - I guess we can close this issue then?

**Comment by Kosat** [comment]
Yes, it's fine now. Thank you. 

Please, close the issue.
