### ISSUE TITLE
Why "Pinned" group is not top of the list?

### ISSUE THREAD

**Issue by ansjinkim** [Dirkster99/MRULib#2]
Hi~
I want to use this library, but something is strange.
When all items are not pinned, if I click the pin of first item, the "Pinned" group is under the "Today" group.
![1](https://user-images.githubusercontent.com/30614195/40958133-1f490332-68d3-11e8-805f-18f9aa3650c9.png)
Other items do not happen this. Is it a bug? How can I fix it?

Thanks in advance.

**Comment by Dirkster99** [comment]
![screenshot_1](https://user-images.githubusercontent.com/2129700/40995973-f524ff38-6900-11e8-9bd5-801a046eec0f.png)
![screenshot2](https://user-images.githubusercontent.com/2129700/40995977-f70c9a0e-6900-11e8-9da3-33d7127de7c0.png)
![screenshot3](https://user-images.githubusercontent.com/2129700/40995979-f8acfe76-6900-11e8-9d46-3697fa7eced5.png)

I can confirm the issue which can be verified with the newest Lastupdate item only - that is - I have tried various resolutions - one of them was to generate the first item with this line:
```
            var now = DateTime.Now;

            retList.UpdateEntry(MRU_Service.Create_Entry(@"C:tmp\t0_now.txt", now.Add(new TimeSpan(0, 0, -1, 0)), false));

```
in [GenerateTestData.cs](https://github.com/Dirkster99/MRULib/blob/master/source/MRUDemo/GenerateTestData.cs) only to find out that another item is now the newest item that shows exactly the same group/sorting issue.

Right now, I am not sure why this is behaving like this only for the newest item?

**Comment by Dirkster99** [comment]
I have analyzed this issue and found a workaround solution which is to completely re-build the bound collection whenever there is only 1 new pinned item to be 'added' into the colleciton:
https://github.com/Dirkster99/MRULib/tree/Fix_Issue2

The fix looks good to me as far as I can see.
Would you be able to test this solution and let me know whether this fixes the problem without introducing new problems?

**Comment by ansjinkim** [comment]
Oh, it's good to me, too. Thank you very much.

I'm using this library through nuget. So when are you going to update fixed release into nuget?

**Comment by Dirkster99** [comment]
I have published a new package version. You can either use:

`Install-Package Dirkster.MRULib -Version 1.0.1
`
to install the package or just wait about 20 mins until the update shows up in the nuget dialog in VS.
Please öet me know if you expierence any other problems.
